name: UClansAddons
version: 1.0.0
main: me.rexyiscool.uclansAddons.UClansAddons
api-version: 1.13
depend: [UltimateClans]
author: rexyiscool
description: Clan callout system for UltimateClans

callout-title: "§c⚠ CLAN CALLOUT ⚠"
message-color: "§e"
title-fade-in: 10    # 0.5 seconds
title-stay: 70       # 3.5 seconds
title-fade-out: 20   # 1 second
callout-sent:
  - ""
  - "&a&lCALLOUT SENT!"
  - "&7Message sent to &e%count%&7 clan member(s)"
  - ""

#Clan CallOut Command CoolDown
callout-cooldown-seconds: 300
#Clan Online Command CoolDown
clanonline-cooldown-seconds: 30